### ISSUE TITLE
no action scenes

### ISSUE THREAD

**Issue by Avihay87** [chadwpalm/HuePlex#14] opened 2023-07-11 14:54 UTC
Hi,
I installed the app on Docker according to the guide.
I had no problem configuring the settings Plex server, connecting the app to my Plex account, and syncing my hue bridge (adding it via IP address).
When adding a new Client profile I get a list of all my devices, as well as the lists of my Rooms and Plex Users.
the problem is with the action scenes of the triggers (Play, Stop, pause, etc.), the only actions I can choose from the list are "none" and "Off".
on the Server tab things look different and I have the options to "Turn on" and "Blink" (I attached images).
I tried both the Latest and Develop Docker images, and they both show the same thing. I also tried changing the container network, I thought of giving it a try, from a custom network to the host network, but still, nothing changed
let me know if more information is needed.
Anyone got any idea what am I missing and how can i fix it
Nothing I have tried has made any changes so I will appreciate any help I can get.
Thanks

Client tab:
![client](https://github.com/chadwpalm/HuePlex/assets/105904450/b9251ff5-b5ab-438c-b6cc-50669cd2addb)

Server tab:
![server](https://github.com/chadwpalm/HuePlex/assets/105904450/77ade95f-3515-40f8-b183-4593db3e8e54)

**Comment by chadwpalm** [comment] 2023-07-11 23:27
> I had no problem configuring the settings Plex server, connecting the app to my Plex account, and syncing my hue bridge (adding it via IP address).

It is acting as if HuePlex can't see your Hue bridge.

If the app made it to the point of asking for an IP address for your Hue bridge, then it means it couldn't discover it using either mDNS or through Hue's servers. The former would suggest that your device hosting the HuePlex docker container is not on the same subnetwork as the Hue bridge. The latter would suggest either your device doesn't have internet access (which I assume it does) or your device and the Hue bridge are not on the same ISP (which I assume they are).

Would you be able to send me your Docker logs for the HuePlex container and maybe I can determine from that what is going on?

**Comment by Avihay87** [comment] 2023-07-14 17:58
Sorry for the late reply.
I think they are on a "different" subnetwork because the hue bridge is connected straight to the router and I got Docker on windows os via wsl2 which is creating a virtual network (I think).
Also, I have the 1st gen hue bridge so maybe this is the reason (or one of them) that it doesn't find the bridge and I need to enter the IP. The weird thing is that the server tab configuration in the app is working and the lights actually blink in the color I set when someone starts playing a video.
As for the log file, how can I send it to you or should I upload it here? If so, is there any info I need to delete before uploading?
Thanks

**Comment by chadwpalm** [comment] 2023-07-15 18:52
I apologize for not being able to dive deeper into this during the week. Work's been pretty busy for me.

Looking at your previous post and screenshots better, I do see now that you actually can choose individual lights and rooms in the Server tab, so it is not an issue with communicating with the bridge as it seems it can do that.

> Also, I have the 1st gen hue bridge so maybe this is the reason (or one of them) that it doesn't find the bridge and I need to enter the IP

Yeah, that's the missing link and what the problem is. Philips has not supported or pushed firmware updates to the 1st gen bridge in over 3 years. The Scenes API that is used in the Client profiles depends on a "group" parameter in the Scene object that wasn't introduced into the API until a time later than when the V1 bridge went EOL. This parameter is needed to figure out which scenes belong to which room/zone in order to separate them out and only show the scenes associated to the specific room you choose.

The bridge discovery methods I described above also rely on later versions of the firmware/API and most likely why they aren't working for you.

Unfortunately, you won't be able to use HuePlex on an outdated bridge that isn't up to date on the latest firmware/API versions. It is my plan to migrate over to v2 of the Hue API sometime in the near future which will most likely make HuePlex completely unusable on the 1st gen bridges.  In fact, as a developer I can tell you that Philips plans to depreciate API v1 sometime in the foreseeable future which is going to render your bridge useless altogether. You might want to consider upgrading it soon.

I'm going to close this issue and update my guide to warn users that the 1st gen Hue bridges will not work with HuePlex.

Chad

**Closed by chadwpalm** 2023-07-15 18:52 UTC

**Comment by Avihay87** [comment] 2023-07-15 19:00
Thanks for your detailed answer.
I guess its time for a new bridge.
